### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by gabin-dongmo**
Changes the project from dynamically to statically typed. It might help improve the code quality, and the developer experience.

### CODE REVIEW

**Comment by Sanix-Darker** [comment]
🔥 HUGE work, sounds really nice !
This is a huge PR... i recommend review/merge small PRs first, then rebase this one before merging it, i don't know what you think about that @ln-dev7 !

**Comment by gabin-dongmo** [comment]
@Sanix-Darker It was pretty straightforward if you ask me, although I would agree that it's kind of a paradigm shift...
However we want to cook it though... @ln-dev7

**Comment by ln-dev7** [comment]
> fire HUGE work, sounds really nice ! This is a huge PR... i recommend review/merge small PRs first, then rebase this one before merging it, i don't know what you think about that @ln-dev7 !

Yes, exactly it would be better to have a fairly stable version in JavaScript and then now remake a total conversion to TS ... @gabin-dongmo

**Comment by gabin-dongmo** [comment]
All things considered, this might not be the right time to make the shift... I'll cancel the pull request for now.
For those interested in further developments with TS though, there's the possibility to check this [alternate version](https://github.com/gabin-dongmo/cameroon-portfolios) I'll be maintaining.

**Pull request closed without merging**
